# Build settings
language: node_js
node_js:
  - "6"

# Notification settings
notifications:
  email:
    on_success: never
    on_failure: change

# SonarQube Settings
addons:
  sonarcloud:
    organization: "lonelyprincess-github"

# Scripts to run before analysis
script:
  - sonar-scanner
